### ISSUE TITLE
Coordinates issue

### ISSUE THREAD

**Issue by OnyxFox** [sky0-1/Nomadic-Tents-1.9#5]
I am trying to craft a small tepee, however it is always giving me the invalid coordinates error. I have been searching for documentation on this issue but haven't found any.

**Comment by sky0-1** [comment]
Make sure you are not shift-clicking to pick up the crafting result.
For some reason, shift-clicking recipes fails to call several important methods.

**Comment by OnyxFox** [comment]
That was it! Thanks
